dist: trusty
sudo: required

services:
  - docker

before_install:
  # TODO: flake8 check
  # - pip install flake8
  # - flake8 --exclude=cnxpublishing/tests *.py cnxpublishing/
  # - flake8 --max-line-length=200 cnxpublishing/tests
  # Stop the local postgres service
  - sudo service postgresql stop
script:
  # Report test coverage to codecov.io
  # See also: https://docs.codecov.io/docs/testing-with-docker
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker-compose build
  - docker-compose up -d
  - sleep 20
  - docker-compose ps
  - docker-compose logs db
  # TODO: report coverage to codecov
  # Note, travis is kinda slow, so we give the connection to the database a longer timeout (60s).
  - docker-compose run $ci_env web wait-for --timeout=240 db:5432 -- wait-for rabbitmq:5672 -- python -m pytest
notifications:
  email: false
