dist: trusty
sudo: required

services:
  - docker

before_install:
  # TODO: flake8 check
  # - pip install flake8
  # - flake8 --exclude=cnxpublishing/tests *.py cnxpublishing/
  # - flake8 --max-line-length=200 cnxpublishing/tests
  # Stop the local postgres service
  - sudo service postgresql stop
script:
  # Report test coverage to codecov.io
  # See also: https://docs.codecov.io/docs/testing-with-docker
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker-compose build
  - docker-compose up -d
  # TODO: report coverage to codecov
  - docker-compose run $ci_env web python -m pytest
notifications:
  email: false
