version: '3.6'

x-app-defaults: &app-defaults
  build: .
  volumes:
    - .:/src
  environment:
    - DB_URL=postgresql://postgres@db/repository
    - DB_SUPER_URL=postgresql://postgres@db/repository
    - AMQP_URL=amqp://guest@rabbitmq:5672//
    - 'USERS=smoo,smoo'
    - MODERATORS=smoo
    - ADMINISTRATORS=smoo
    - MATHMLCLOUD_URL
    - MEMCACHE_HOST
    - EXERCISES_URL
    # Use the docker aware version of the testing configuration file
    - TESTING_CONFIG=docker-testing.ini

services:
  db:
    image: openstax/cnx-db:latest
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management

  web:
    <<: *app-defaults
    command: bash -c "pserve $${PYRAMID_INI}"
    ports:
      - "6543"

  publishing-worker:
    <<: *app-defaults
    command: bash -c "celery worker -A cnxpublishing -Q default,deferred --loglevel debug"

  channel-processing:
    <<: *app-defaults
    command: bash -c "cnx-publishing-channel-processing $${PYRAMID_INI}"

volumes:
  pgdata:
